import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../../utils/trpc";

import CustomInput from "../../components/CustomInput";
import CustomButton from "../../components/CustomButton";
import { NextPage } from "next";
import { useSnackbar } from "notistack";
import { useRouter } from "next/router";

//redux
import { registerSuccess } from "../../redux/slices/auth";
import { useDispatch } from "react-redux";

interface SignupData {
  username: string;
  email: string;
  password: string;
  cpassword: string;
}

const Signup: NextPage = () => {
  const [data, setData] = useState<SignupData>({
    username: "",
    email: "",
    password: "",
    cpassword: "",
  });
  const { enqueueSnackbar } = useSnackbar();
  const router = useRouter();
  const dispatch = useDispatch();

  const signupMutation = trpc.useMutation(["auth.signup"], {
    onError: (err) => {
      console.log(err, "here");
      enqueueSnackbar(err.message, { variant: "error" });
    },
    onSuccess: (data) => {
      console.log(data);
      localStorage.setItem("accessToken", data.token);
      dispatch(registerSuccess({ user: data.user }));
      router.push("/home");
    },
  });

  const handleSignupClick = () => {
    if (data.password !== data.cpassword) {
      alert("passwords do not match!");
      return;
    }
    const fdata = {
      username: data.username,
      password: data.password,
      email: data.email,
    };
    signupMutation.mutate(fdata);
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setData({
      ...data,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <>
      <Head>
        <title>Signup:Social3.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col items-center justify-center bg-background1 text-surface">
        <div className="flex h-fit flex-col items-center gap-12  rounded-md border-2 border-primary bg-background1 p-4 py-5 shadow-lg sm:w-4/5 md:w-2/3 lg:w-1/3">
          <h1 className="text-xl">BECOME A PART OF SOCIAL</h1>
          <CustomInput
            label="Username"
            name="username"
            value={data.username}
            onChange={handleChange}
          />
          <CustomInput
            label="Email"
            name="email"
            value={data.email}
            onChange={handleChange}
          />
          <CustomInput
            label="Password"
            name="password"
            value={data.password}
            type="password"
            onChange={handleChange}
          />
          <CustomInput
            label="Confirm Password"
            name="cpassword"
            value={data.cpassword}
            type="password"
            onChange={handleChange}
          />
          <CustomButton
            disabled={signupMutation.isLoading}
            onClick={handleSignupClick}
          >
            SIGN UP
          </CustomButton>
        </div>
      </main>
    </>
  );
};

export default Signup;
